import type { DefaultTheme } from 'vitepress'

const sidebarOther: DefaultTheme.SidebarGroup = {
  text: 'Other',
  items: [
    // 置顶文章 - 始终保持在最前面
    { text: 'Jack核心投资策略', link: '/Other/docs/Jack核心投资策略总结' },
    { text: 'Jack要加油的专属会员内容', link: '/Other/docs/Jack要加油的专属会员内容' },
    { text: '2030年，Jack最有把握的5个判断', link: '/Other/docs/2030年，Jack最有把握的5个判断' },
    { text: '六年之约，不靠鸡血，靠系统改变人生', link: '/Other/docs/六年之约，不靠鸡血，靠系统改变人生' },
    { text: '未来20年，普通人靠什么翻身？', link: '/Other/docs/未来20年，普通人靠什么翻身？' },
    { text: '未来最值钱的能力，不是会用AI，而是专注力', link: '/Other/docs/未来最值钱的能力，不是会用AI，而是专注力' },
    { text: '未来真正稀缺的，可能不是信息，而是判断力', link: '/Other/docs/未来真正稀缺的，可能不是信息，而是判断力' },
    { text: 'AI时代，阅读、专注、提问，比背答案重要100倍', link: '/Other/docs/AI时代，阅读、专注、提问，比背答案重要100倍' },

    // 系列文章 - 按编号排序
    { text: '真正高级的人，不需要天天讲大道理', link: '/Other/docs/真正高级的人，不需要天天讲大道理' },
    { text: '中国普通人拉开差距的现实规律', link: '/Other/docs/中国普通人拉开差距的现实规律' },
    { text: '先调状态，再改变生活', link: '/Other/docs/先调状态，再改变生活' },
    { text: '去黄石别错过大提顿', link: '/Other/docs/去黄石别错过大提顿' },
    { text: '美国西部平原的震撼与思考', link: '/Other/docs/美国西部平原的震撼与思考' },
    { text: '密西西比河三角洲：几千年积累的力量', link: '/Other/docs/密西西比河三角洲：几千年积累的力量' },
    { text: '海明威：把生活变成小说', link: '/Other/docs/海明威：把生活变成小说' },
    { text: '20-30岁，多看看人物传记', link: '/Other/docs/20-30岁，多看看人物传记' },
    { text: '20-30岁到底应该读什么', link: '/Other/docs/20-30岁到底应该读什么' },
    { text: '仅靠阅读能否真正提升认知', link: '/Other/docs/仅靠阅读能否真正提升认知' },
    { text: '读完传记之后', link: '/Other/docs/读完传记之后' },
    { text: '消费观：不鸡汤，讲实在的', link: '/Other/docs/消费观：不鸡汤，讲实在的' },
    { text: '未来十年值得投资的五样东西', link: '/Other/docs/未来十年值得投资的五样东西' },
    { text: '科斯托拉尼：欧洲巴菲特的投机哲学', link: '/Other/docs/科斯托拉尼：欧洲巴菲特的投机哲学' },
    { text: '如何提升口才和表达', link: '/Other/docs/如何提升口才和表达' },
    { text: '表达不是天生的，可以练出来', link: '/Other/docs/表达不是天生的，可以练出来' },
    { text: '聊聊运气这件事', link: '/Other/docs/聊聊运气这件事' },
    { text: '算命背后：行为习惯与人生趋势', link: '/Other/docs/算命背后：行为习惯与人生趋势' },
    { text: '戏剧《小镇》拆解：希望让你平和', link: '/Other/docs/戏剧《小镇》拆解：希望让你平和' },
    { text: '勇敢变好，和家人的关系才能变好', link: '/Other/docs/勇敢变好，和家人的关系才能变好' },
    { text: '学区负责人年度评估："专业达标"', link: '/Other/docs/学区负责人年度评估：专业达标' },
    { text: '真正厉害的沟通：让别人听懂你', link: '/Other/docs/真正厉害的沟通：让别人听懂你' },
    { text: '2周50篇文章20000字的积累', link: '/Other/docs/2周50篇文章20000字的积累' },
    { text: '亚利桑那的仙人掌：熬得住寂寞才配得上穿越荒漠', link: '/Other/docs/亚利桑那的仙人掌：熬得住寂寞才配得上穿越荒漠' },
    { text: '直播内容和专属会员内容', link: '/Other/docs/直播内容和专属会员内容' },

    // 独立文章 - 按时间排序
    { text: '影响健康的因素', link: '/Other/docs/影响健康的因素' },
    { text: '昨夜梦回云南：茶马古道的故事', link: '/Other/docs/昨夜梦回云南：茶马古道的故事' },
    { text: '普通人最大的误区：不懂概率思维', link: '/Other/docs/普通人最大的误区：不懂概率思维' },
    { text: '美光、闪迪大涨：揭开AI背后隐藏的真金白银', link: '/Other/docs/美光、闪迪大涨：揭开AI背后隐藏的真金白银' },
    { text: '一部电影看懂为什么一定要储蓄', link: '/Other/docs/一部电影看懂为什么一定要储蓄' },
    { text: '《Valkyrie》：当整个时代犯错，一个人还能坚持良知吗', link: '/Other/docs/《Valkyrie》：当整个时代犯错，一个人还能坚持良知吗' },
    { text: '父母给孩子最好的爱：让他拥有管理自己世界的能力', link: '/Other/docs/父母给孩子最好的爱：让他拥有管理自己世界的能力' },
    { text: '不会不代表不会：专注思考的过程足以创造进步', link: '/Other/docs/不会不代表不会：专注思考的过程足以创造进步' },
    { text: '教育如果太早只剩评分，孩子会忘记为什么喜欢一件事', link: '/Other/docs/教育如果太早只剩评分，孩子会忘记为什么喜欢一件事' },
    { text: '你想成为什么样的人，是你的选择', link: '/Other/docs/你想成为什么样的人，是你的选择' },
    { text: '年轻时最难受的，不是没钱，而是没人真正理解你', link: '/Other/docs/年轻时最难受的，不是没钱，而是没人真正理解你' },
    { text: '方向决定终点，能力只是放大器', link: '/Other/docs/方向决定终点，能力只是放大器' },
    { text: '扔硬币的直播切片：别编答案糊弄自己', link: '/Other/docs/扔硬币的直播切片：别编答案糊弄自己' },
    { text: '23人中至少两人同一天生日的概率', link: '/Other/docs/23人中至少两人同一天生日的概率' },
    { text: '教孩子和钱打交道：比辅导学习更重要', link: '/Other/docs/教孩子和钱打交道：比辅导学习更重要' },
    { text: '做一个靠谱的人，好运和幸福会被你吸引', link: '/Other/docs/做一个靠谱的人，好运和幸福会被你吸引' },
    { text: 'Jack的一天：没大家想象得那么复杂', link: '/Other/docs/Jack的一天：没大家想象得那么复杂' },
    { text: '古埃及方尖碑是怎么建造出来的', link: '/Other/docs/古埃及方尖碑是怎么建造出来的' },

    // 其他文章
    { text: '50美分的快乐与一场被认真对待的青春', link: '/Other/docs/50美分的快乐与一场被认真对待的青春' },
    { text: 'AI到底赚到钱了吗', link: '/Other/docs/AI到底赚到钱了吗' },
    { text: '一号公路的约定', link: '/Other/docs/一号公路的约定' },
    { text: '去抱一棵树吧，它会告诉你人生的答案', link: '/Other/docs/去抱一棵树吧，它会告诉你人生的答案' },
    { text: '听完这首歌，我终于明白：有些人的痛苦，会长成光', link: '/Other/docs/听完这首歌，我终于明白：有些人的痛苦，会长成光' },
    { text: '拉开人与人差距的不是AI，而是提问的能力', link: '/Other/docs/拉开人与人差距的不是AI，而是提问的能力。' },
    { text: '没有本金，AI机会来了也不是你的', link: '/Other/docs/没有本金，AI机会来了也不是你的' },
    { text: '深夜耳机必听：佛蒙特月光里的极致温柔', link: '/Other/docs/深夜耳机必听：佛蒙特月光里的极致温柔' },
    { text: '清晨六点，一杯咖啡，和几十年前的新英格兰', link: '/Other/docs/清晨六点，一杯咖啡，和几十年前的新英格兰' },
    { text: '焦虑的解药：区分控制圈和影响圈', link: '/Other/docs/焦虑的解药：区分控制圈和影响圈' },
    { text: '看完罗马复原图突然顿悟：人性两千年没变，真正厉害的人都在悄悄\u201C搞基建\u201D', link: '/Other/docs/看完罗马复原图突然顿悟：人性两千年没变，真正厉害的人都在悄悄\u201C搞基建\u201D' },
    { text: '站在格伦峡谷大坝前，Jack读懂了35岁的成长', link: '/Other/docs/站在格伦峡谷大坝前，Jack读懂了35岁的成长' },
    { text: '致所有被低估的女孩：请像她一样，绝不降低你的人生高度', link: '/Other/docs/致所有被低估的女孩：请像她一样，绝不降低你的人生高度' },
    { text: '阅读最大的价值，从来不是记住一本书，而是换一种活法', link: '/Other/docs/阅读最大的价值，从来不是记住一本书，而是换一种活法' },
    { text: '除了祝你好成绩，我更想和你聊聊高考后的这几年', link: '/Other/docs/除了祝你好成绩，我更想和你聊聊高考后的这几年' },
  ],
}

export default sidebarOther
